### ISSUE TITLE
How can I use my own data

### ISSUE THREAD

**Issue by anas-899** [brine-io/u-net-segmentation-example#1]
Hi,
I am wondering if there is anyway for using my own data as brine package or build method to generate bcolz folder for a specific images folder

**Comment by hanrelan** [comment]
Hi,
It's not documented but you can create your own brine package. The steps are:
1) Install brine:
`pip install brine-io`
2) Assuming you have a folder called `images/` and the files are called `image1.png` and `image1_mask.png`, create an annotations file called `images/annotations.csv`. The file should look something like this:
```
image,mask
image1.png,image1_mask.png
other_image.png,other_image_mask.png
... (for all the images and masks that you have)
```
3) Create a file called `images/config.json` to specify the schema with these contents:
```
{
        "path": "annotations.csv",
        "columns": [
                {
                        "name": "image",
                        "type": "image"
                },
                {
                        "name": "mask",
                        "type": "image"
                }
        ]
}
```
4) Then you can build the brine package by executing:
`brine build anas/my-images-with-masks --config images/config.json`
5) Now you can swap out the package name in the example so:
`chairs = brine.load_dataset('rohan/chairs-with-masks')`
becomes
`chairs = brine.load_dataset('anas/my-images-with-masks')`

And that should let you use your own dataset. Note you may need to change the threshold values in the `fix_mask` function if your masks aren't colored the same way. Hope that helps

**Comment by anas-899** [comment]
Thanks @hanrelan.. It worked like a charm
